//

//
// ============================
//// 01...
// statement: Write a JavaScript Program to grab the content from html file and console log it ...

// write your code here ...
// []

//
// ============================
//// 02...
// statement: Write a JavaScript Program to grab the content from html file ("Hello world") and change it to "Good morning" ...

// write your code here ...
// []

//
// ============================
//// 03...
// statement: Write a JavaScript Program and take the below variables and print the expected output to the browser ...
let fname = "John";
let lName = "Doe";
// Epected output: Good morning, Jonh Doe.

// write your code here ...
// []

//
// ============================
//// 04...
// statement: Write a JavaScript Program and grab the <p> element and change the color of that tag to "#cdb4db" ...

// write your code here ...
// []

//
// ============================
//// 05...
// statement: Write a JavaScript Program and grab the <img> element with id and change the path of that and update the picture with new path ...

// write your code here ...
// []

//
// ============================
//// 06...
// statement: Write a JavaScript Program to change the content of first <p> tag and change the content of that to "Content changed ..." ...

// write your code here ...
// []

//
// ============================
//// 07...
// statement: Write a JavaScript Program to change the font weight to 700 or 900 ...

// write your code here ...
// []

//
// ============================
//// 08...
// statement: Write a JavaScript Program to change the color of <div> to "#d4a373"...

// write your code here ...
// []
