//

//
// ============================
//// 01...
// statement: Write a JavaScript Program and grab the <img> element with id and change the path of that and update the picture with new path, when user clicks on button ...

// write your code here ...
// []

//
// ============================
//// 02...
// statement: Write a JavaScript Program to hide the <div> element when user hovers on another <div> element ...

// write your code here ...
// []

//
// ============================
//// 03...
// statement: Write a JavaScript Program to remove the one <p> tag when user clicks on button ...

// write your code here ...
// []

//
// ============================
//// 04...
// statement: Write a JavaScript Program to open a new window on button click ...

// write your code here ...
// []

//
// ============================
//// 05...
// statement: Write a JavaScript Program to print the host name of current window ...

// write your code here ...
// []

//
// ============================
//// 06...
// statement: Write a JavaScript Program to print the current page URL ...

// write your code here ...
// []

//
// ============================
//// 07...
// statement: Write a JavaScript Program to print the current page pathname ...

// write your code here ...
// []

//
// ============================
//// 08...
// statement: Write a JavaScript Program, where, create 2 button named "Next" and "Previous" and onClicking them redirect user to next or back (use window.history) ...

// write your code here ...
// []

//
// ============================
//// 09...
// statement: Write a JavaScript Program to print the current Operating System name to console (use navigator) ...

// write your code here ...
// []

//
// ============================
//// 010...
// statement: Write a JavaScript Program to print, if your browser is connected with active internet connection or not (use navigator) ...

// write your code here ...
// []
